/* Generated by Yosys 0.13+15 (git sha1 bc027b2ca, clang 13.0.0-2 -fPIC -Os) */

module spi_master_rtl(i_clk, i_rst, i_data, i_send, o_data, o_busy, i_miso, o_mosi, o_sclk, o_ss);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [27:0] _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  input i_clk;
  input [27:0] i_data;
  input i_miso;
  input i_rst;
  input i_send;
  output o_busy;
  output [27:0] o_data;
  output o_mosi;
  reg o_mosi;
  output o_sclk;
  output o_ss;
  wire s_bit;
  reg s_bit_in;
  wire s_inter;
  wire s_sin_en;
  wire s_sin_wrt;
  wire s_sout_en;
  wire s_sout_wrt;
  reg [2:0] s_state;
  wire [2:0] s_state_next;
  wire s_watchdog_we;
  wire \shift.i_bit ;
  wire \shift.i_clk_p ;
  wire [27:0] \shift.i_data ;
  wire \shift.i_en ;
  wire \shift.i_rst_n ;
  wire \shift.i_wrt ;
  wire \shift.o_bit ;
  wire [27:0] \shift.o_data ;
  reg [27:0] \shift.s_shifter ;
  wire \watchdog.i_clk_p ;
  wire [5:0] \watchdog.i_cycles ;
  wire \watchdog.i_rst_n ;
  wire \watchdog.i_we ;
  wire \watchdog.o_inter ;
  reg [5:0] \watchdog.s_count ;
  wire [5:0] \watchdog.s_count_next ;
  reg [5:0] \watchdog.s_cycles ;
  assign _001_ = ~s_state[1];
  assign _002_ = ~s_state[2];
  assign s_sout_wrt = s_state[0] & _001_;
  assign _003_ = s_state[0] | s_state[1];
  assign _004_ = ~_003_;
  assign _005_ = s_state[1] & s_state[2];
  assign _006_ = _001_ | _002_;
  assign o_ss = _004_ | _005_;
  assign s_sout_en = ~o_ss;
  assign _007_ = s_state[2] | _003_;
  assign _008_ = _002_ & _003_;
  assign o_busy = _006_ & _007_;
  assign _000_ = i_send | _007_;
  assign _009_ = s_state[0] & s_state[1];
  assign _010_ = ~_009_;
  assign o_sclk = _008_ & _010_;
  assign _011_ = s_state[0] | _002_;
  assign s_state_next[0] = _010_ & _011_;
  assign _012_ = s_inter & _009_;
  assign _013_ = ~_012_;
  assign _014_ = _004_ | _012_;
  assign s_state_next[1] = _008_ & _013_;
  assign s_state_next[2] = _002_ & _014_;
  always @(posedge i_clk, negedge i_rst)
    if (!i_rst) s_state[0] <= 1'h0;
    else if (_000_) s_state[0] <= s_state_next[0];
  always @(posedge i_clk, negedge i_rst)
    if (!i_rst) s_state[1] <= 1'h0;
    else if (_000_) s_state[1] <= s_state_next[1];
  always @(posedge i_clk, negedge i_rst)
    if (!i_rst) s_state[2] <= 1'h0;
    else if (_000_) s_state[2] <= s_state_next[2];
  always @(posedge o_sclk, negedge i_rst)
    if (!i_rst) s_bit_in <= 1'h0;
    else s_bit_in <= i_miso;
  always @(negedge o_sclk, negedge i_rst)
    if (!i_rst) o_mosi <= 1'h0;
    else o_mosi <= s_bit;
  assign _015_[20] = _047_ | _048_;
  assign _049_ = \shift.i_wrt  & \shift.i_data [21];
  assign _050_ = _063_ & \shift.s_shifter [20];
  assign _015_[21] = _049_ | _050_;
  assign _051_ = \shift.i_wrt  & \shift.i_data [22];
  assign _052_ = _063_ & \shift.s_shifter [21];
  assign _015_[22] = _051_ | _052_;
  assign _053_ = \shift.i_wrt  & \shift.i_data [23];
  assign _054_ = _063_ & \shift.s_shifter [22];
  assign _015_[23] = _053_ | _054_;
  assign _055_ = \shift.i_wrt  & \shift.i_data [24];
  assign _056_ = _063_ & \shift.s_shifter [23];
  assign _015_[24] = _055_ | _056_;
  assign _057_ = \shift.i_wrt  & \shift.i_data [25];
  assign _058_ = _063_ & \shift.s_shifter [24];
  assign _015_[25] = _057_ | _058_;
  assign _059_ = \shift.i_wrt  & \shift.i_data [26];
  assign _060_ = _063_ & \shift.s_shifter [25];
  assign _015_[26] = _059_ | _060_;
  assign _061_ = \shift.i_wrt  & \shift.i_data [27];
  assign _062_ = _063_ & \shift.s_shifter [26];
  assign _015_[27] = _061_ | _062_;
  assign _063_ = ~\shift.i_wrt ;
  assign _064_ = \shift.i_data [0] & \shift.i_wrt ;
  assign _065_ = \shift.i_bit  & _063_;
  assign _015_[0] = _064_ | _065_;
  assign _066_ = \shift.i_wrt  & \shift.i_data [1];
  assign _067_ = _063_ & \shift.s_shifter [0];
  assign _015_[1] = _066_ | _067_;
  assign _068_ = \shift.i_wrt  & \shift.i_data [2];
  assign _069_ = _063_ & \shift.s_shifter [1];
  assign _015_[2] = _068_ | _069_;
  assign _070_ = \shift.i_wrt  & \shift.i_data [3];
  assign _071_ = _063_ & \shift.s_shifter [2];
  assign _015_[3] = _070_ | _071_;
  assign _072_ = \shift.i_wrt  & \shift.i_data [4];
  assign _016_ = _063_ & \shift.s_shifter [3];
  assign _015_[4] = _072_ | _016_;
  assign _017_ = \shift.i_wrt  & \shift.i_data [5];
  assign _018_ = _063_ & \shift.s_shifter [4];
  assign _015_[5] = _017_ | _018_;
  assign _019_ = \shift.i_wrt  & \shift.i_data [6];
  assign _020_ = _063_ & \shift.s_shifter [5];
  assign _015_[6] = _019_ | _020_;
  assign _021_ = \shift.i_wrt  & \shift.i_data [7];
  assign _022_ = _063_ & \shift.s_shifter [6];
  assign _015_[7] = _021_ | _022_;
  assign _023_ = \shift.i_wrt  & \shift.i_data [8];
  assign _024_ = _063_ & \shift.s_shifter [7];
  assign _015_[8] = _023_ | _024_;
  assign _025_ = \shift.i_wrt  & \shift.i_data [9];
  assign _026_ = _063_ & \shift.s_shifter [8];
  assign _015_[9] = _025_ | _026_;
  assign _027_ = \shift.i_wrt  & \shift.i_data [10];
  assign _028_ = _063_ & \shift.s_shifter [9];
  assign _015_[10] = _027_ | _028_;
  assign _029_ = \shift.i_wrt  & \shift.i_data [11];
  assign _030_ = _063_ & \shift.s_shifter [10];
  assign _015_[11] = _029_ | _030_;
  assign _031_ = \shift.i_wrt  & \shift.i_data [12];
  assign _032_ = _063_ & \shift.s_shifter [11];
  assign _015_[12] = _031_ | _032_;
  assign _033_ = \shift.i_wrt  & \shift.i_data [13];
  assign _034_ = _063_ & \shift.s_shifter [12];
  assign _015_[13] = _033_ | _034_;
  assign _035_ = \shift.i_wrt  & \shift.i_data [14];
  assign _036_ = _063_ & \shift.s_shifter [13];
  assign _015_[14] = _035_ | _036_;
  assign _037_ = \shift.i_wrt  & \shift.i_data [15];
  assign _038_ = _063_ & \shift.s_shifter [14];
  assign _015_[15] = _037_ | _038_;
  assign _039_ = \shift.i_wrt  & \shift.i_data [16];
  assign _040_ = _063_ & \shift.s_shifter [15];
  assign _015_[16] = _039_ | _040_;
  assign _041_ = \shift.i_wrt  & \shift.i_data [17];
  assign _042_ = _063_ & \shift.s_shifter [16];
  assign _015_[17] = _041_ | _042_;
  assign _043_ = \shift.i_wrt  & \shift.i_data [18];
  assign _044_ = _063_ & \shift.s_shifter [17];
  assign _015_[18] = _043_ | _044_;
  assign _045_ = \shift.i_wrt  & \shift.i_data [19];
  assign _046_ = _063_ & \shift.s_shifter [18];
  assign _015_[19] = _045_ | _046_;
  assign _047_ = \shift.i_wrt  & \shift.i_data [20];
  assign _048_ = _063_ & \shift.s_shifter [19];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [0] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [0] <= _015_[0];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [1] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [1] <= _015_[1];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [2] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [2] <= _015_[2];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [3] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [3] <= _015_[3];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [4] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [4] <= _015_[4];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [5] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [5] <= _015_[5];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [6] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [6] <= _015_[6];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [7] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [7] <= _015_[7];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [8] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [8] <= _015_[8];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [9] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [9] <= _015_[9];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [10] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [10] <= _015_[10];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [11] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [11] <= _015_[11];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [12] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [12] <= _015_[12];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [13] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [13] <= _015_[13];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [14] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [14] <= _015_[14];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [15] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [15] <= _015_[15];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [16] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [16] <= _015_[16];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [17] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [17] <= _015_[17];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [18] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [18] <= _015_[18];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [19] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [19] <= _015_[19];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [20] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [20] <= _015_[20];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [21] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [21] <= _015_[21];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [22] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [22] <= _015_[22];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [23] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [23] <= _015_[23];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [24] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [24] <= _015_[24];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [25] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [25] <= _015_[25];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [26] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [26] <= _015_[26];
  always @(posedge \shift.i_clk_p , negedge \shift.i_rst_n )
    if (!\shift.i_rst_n ) \shift.s_shifter [27] <= 1'h0;
    else if (\shift.i_en ) \shift.s_shifter [27] <= _015_[27];
  assign _073_ = ~\watchdog.s_count [5];
  assign _074_ = ~\watchdog.s_count [4];
  assign _075_ = ~\watchdog.s_count [0];
  assign _076_ = ~\watchdog.i_we ;
  assign _077_ = \watchdog.s_count [0] | \watchdog.s_count [1];
  assign _078_ = \watchdog.s_count [2] | _077_;
  assign _079_ = \watchdog.s_count [3] | _078_;
  assign _080_ = ~_079_;
  assign _081_ = _074_ & _080_;
  assign _082_ = \watchdog.s_count [4] | _079_;
  assign _083_ = _073_ & _081_;
  assign _084_ = \watchdog.s_count [5] | _082_;
  assign _085_ = \watchdog.s_cycles [1] | \watchdog.s_cycles [0];
  assign _086_ = \watchdog.s_cycles [3] | \watchdog.s_cycles [2];
  assign _087_ = \watchdog.s_cycles [5] | \watchdog.s_cycles [4];
  assign _088_ = _086_ | _087_;
  assign _089_ = _085_ | _088_;
  assign _090_ = _076_ & _089_;
  assign \watchdog.o_inter  = _083_ & _090_;
  assign _091_ = \watchdog.s_cycles [0] & _083_;
  assign _092_ = _075_ & _084_;
  assign _093_ = _091_ | _092_;
  assign _094_ = _076_ & _093_;
  assign _095_ = \watchdog.i_we  & \watchdog.i_cycles [0];
  assign \watchdog.s_count_next [0] = _094_ | _095_;
  assign _096_ = _075_ ^ \watchdog.s_count [1];
  assign _097_ = _084_ & _096_;
  assign _098_ = \watchdog.s_cycles [1] & _083_;
  assign _099_ = _097_ | _098_;
  assign _100_ = _076_ & _099_;
  assign _101_ = \watchdog.i_we  & \watchdog.i_cycles [1];
  assign \watchdog.s_count_next [1] = _100_ | _101_;
  assign _102_ = \watchdog.s_cycles [2] | _084_;
  assign _103_ = \watchdog.s_count [2] ^ _077_;
  assign _104_ = \watchdog.i_we  & \watchdog.i_cycles [2];
  assign _105_ = \watchdog.i_we  | _103_;
  assign _106_ = ~_105_;
  assign _107_ = _102_ & _106_;
  assign \watchdog.s_count_next [2] = _104_ | _107_;
  assign _108_ = \watchdog.s_cycles [3] | _084_;
  assign _109_ = \watchdog.s_count [3] ^ _078_;
  assign _110_ = \watchdog.i_we  & \watchdog.i_cycles [3];
  assign _111_ = \watchdog.i_we  | _109_;
  assign _112_ = ~_111_;
  assign _113_ = _108_ & _112_;
  assign \watchdog.s_count_next [3] = _110_ | _113_;
  assign _114_ = \watchdog.s_count [5] | \watchdog.s_cycles [4];
  assign _115_ = _081_ & _114_;
  assign _116_ = \watchdog.s_count [4] & _079_;
  assign _117_ = _076_ | \watchdog.i_cycles [4];
  assign _118_ = \watchdog.i_we  | _116_;
  assign _119_ = _115_ | _118_;
  assign \watchdog.s_count_next [4] = _117_ & _119_;
  assign _120_ = \watchdog.s_cycles [5] & _083_;
  assign _121_ = \watchdog.s_count [5] & _082_;
  assign _122_ = _076_ | \watchdog.i_cycles [5];
  assign _123_ = \watchdog.i_we  | _121_;
  assign _124_ = _120_ | _123_;
  assign \watchdog.s_count_next [5] = _122_ & _124_;
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_cycles [0] <= 1'h0;
    else if (\watchdog.i_we ) \watchdog.s_cycles [0] <= \watchdog.i_cycles [0];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_cycles [1] <= 1'h0;
    else if (\watchdog.i_we ) \watchdog.s_cycles [1] <= \watchdog.i_cycles [1];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_cycles [2] <= 1'h0;
    else if (\watchdog.i_we ) \watchdog.s_cycles [2] <= \watchdog.i_cycles [2];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_cycles [3] <= 1'h0;
    else if (\watchdog.i_we ) \watchdog.s_cycles [3] <= \watchdog.i_cycles [3];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_cycles [4] <= 1'h0;
    else if (\watchdog.i_we ) \watchdog.s_cycles [4] <= \watchdog.i_cycles [4];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_cycles [5] <= 1'h0;
    else if (\watchdog.i_we ) \watchdog.s_cycles [5] <= \watchdog.i_cycles [5];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_count [0] <= 1'h0;
    else \watchdog.s_count [0] <= \watchdog.s_count_next [0];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_count [1] <= 1'h0;
    else \watchdog.s_count [1] <= \watchdog.s_count_next [1];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_count [2] <= 1'h0;
    else \watchdog.s_count [2] <= \watchdog.s_count_next [2];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_count [3] <= 1'h0;
    else \watchdog.s_count [3] <= \watchdog.s_count_next [3];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_count [4] <= 1'h0;
    else \watchdog.s_count [4] <= \watchdog.s_count_next [4];
  always @(posedge \watchdog.i_clk_p , negedge \watchdog.i_rst_n )
    if (!\watchdog.i_rst_n ) \watchdog.s_count [5] <= 1'h0;
    else \watchdog.s_count [5] <= \watchdog.s_count_next [5];
  assign s_sin_en = 1'h0;
  assign s_sin_wrt = 1'h0;
  assign s_watchdog_we = s_sout_wrt;
  assign \watchdog.i_clk_p  = o_sclk;
  assign \watchdog.i_cycles  = 6'h1c;
  assign \watchdog.i_rst_n  = i_rst;
  assign \watchdog.i_we  = s_sout_wrt;
  assign s_inter = \watchdog.o_inter ;
  assign \shift.o_bit  = \shift.s_shifter [27];
  assign \shift.o_data  = \shift.s_shifter ;
  assign \shift.i_bit  = s_bit_in;
  assign \shift.i_clk_p  = o_sclk;
  assign \shift.i_data  = i_data;
  assign \shift.i_en  = s_sout_en;
  assign \shift.i_rst_n  = i_rst;
  assign \shift.i_wrt  = s_sout_wrt;
  assign s_bit = \shift.o_bit ;
  assign o_data = \shift.o_data ;
endmodule
